### ISSUE TITLE
Set max-height on the Tag list

### ISSUE THREAD

**Issue by peduarte** [artisologic/github-stars-tagger#16]
Might be a good idea to set a max-height on the Filter by Tags list... 
https://www.dropbox.com/s/hcx0s6ivtpzcfes/Screenshot%202015-09-18%2016.20.40.png?dl=0

Getting long!

**Comment by artisologic** [comment]
Hey @peduarte that's probably a good idea. Something that comes up after using it a little while I suppose.

* Option 1: simply set a max height, and `overflow: scroll`
* Option 2: implement a simple **Show more/Show less** mechanism

What's your gut feel?

**Comment by peduarte** [comment]
I think a `max-height` is a nicer approach, it's fast to do and you maintain the UI's height all the time.

The problem I see with Option 2, is that after clicking **show more** you will be left with the long list once again, so it doesn't feel like a good solution to me

**Comment by artisologic** [comment]
That's a good argument for option 1.
One thing with option 1 though is that we need to make sure it's clear there are more items to see.

Maybe deliberately set the max-height to break mid-way through a line? Although it's a bit fragile, but if defined in `em` should be fine.

Other tricks involve subtle shadows in design, but doesn't seem to suit GH's style.

**Comment by peduarte** [comment]
Yeah I see what you mean...  This is only an issue for people using OSX with the scroll invisible, like us :stuck_out_tongue: For everyone else, they will see the scrollbar, which will probably look ugly...

**Comment by artisologic** [comment]
One potential small UX tweak that could help would be to show the total number of tags next to "Filter by tags"?

**Comment by artisologic** [comment]
How about that?

![screen shot 2015-09-21 at 11 15 14](https://cloud.githubusercontent.com/assets/1539897/9989626/12f00004-6052-11e5-9f09-a83c1cb615bd.png)

I deliberately removed the margin top on the `hr` separator so show that it's cut.

**Comment by peduarte** [comment]
Yeah, that works, but how does it look if you change your settings so the scrollbar is always visible?

**Comment by artisologic** [comment]
bad? :)

**Comment by artisologic** [comment]
![screen shot 2015-09-21 at 11 20 10](https://cloud.githubusercontent.com/assets/1539897/9989699/bd816c88-6052-11e5-8661-2edbdd1a5f91.png)

**Comment by peduarte** [comment]
lol
