### ISSUE TITLE
Some suggestion

### ISSUE THREAD

**Issue by harryzjm** [artisologic/github-stars-tagger#21]
First, This extension is so good, Thanks for you put it open source.  
Next, If you can add a tag name Untag , which to put untag star in it, it must be great.

**Comment by artisologic** [comment]
@harryzjm thanks for the kind words.

Unfortunately, what you're asking for is currently technically not possible given the current backend architecture as I am relying on explicit tagging saved via `chrome.storage.sync`.

In other words, this doesn't use the github API at all, so I don't have a way to know all of your starred repos. It's only when you add tag to a starred repo that it is linked and saved via `chrome.storage.sync`.

I will close this now.
