### ISSUE TITLE
Can't work now?

### ISSUE THREAD

**Issue by jp1017** [artisologic/github-stars-tagger#23]
I tagged a stared github repo, but the tags missing when I refresh or restart Chrome.

what's wrong?

Chrome: `版本 50.0.2661.102 m`
OS: `Win 10 14342`

**Comment by artisologic** [comment]
Hi,

I cannot reproduce the issue.
Does this happen consistently?

**Comment by jp1017** [comment]
Yes, everytime.

**Comment by artisologic** [comment]
Have you tried to remove the extension and re-install it?

**Comment by jp1017** [comment]
@artisologic 
Oh, It working when reinstall this amazing plugin.

But, My tags had lost, so, how to restore them. :sob:

**Comment by artisologic** [comment]
I am not sure how to restore them to be honest. The sync is handled by google so not much I can do unfortunately, I will try and look into it.

**Comment by sinchang** [comment]
can't work in 

Chrome: 57.0.2987.133 (64-bit)

**Comment by artisologic** [comment]
@sinchang I am running the exact same version of Chrome as you and everything still works fine for me. Can you give a bit more info about what's not working? Are you definitely looking at the stars page? (https://github.com/stars)

**Comment by sinchang** [comment]
@artisologic sorry, can't work because I visit https://github.com/sinchang?tab=stars, working in https://github.com/stars. thanks.

**Comment by artisologic** [comment]
Cool! 🙂
