### ISSUE TITLE
Extension doesn't work with the last Github update

### ISSUE THREAD

**Issue by jpardogo** [artisologic/github-stars-tagger#24]

**Comment by jpardogo** [comment]
It does work in https://github.com/stars but not in the profile tab stars.

**Comment by gabrielgodoy** [comment]
I have been working on a extension similar to that, check it out:
https://github.com/gabrielgodoy/github-stars-manager

**Comment by jpardogo** [comment]
@gabrielgodoy Cheers, I will take a look!

**Comment by artisologic** [comment]
@jpardogo Hi, the latest version (1.0.3) brings back full compatibility for the https://github.com/stars page. Sorry for the wait.
