### ISSUE TITLE
Project discontinued?

### ISSUE THREAD

**Issue by cesards** [artisologic/github-stars-tagger#26]
Is this project discontinued? Since it looks the maintainer is not active, I'm tempted to fork this repo and fix some stuff.

**Comment by artisologic** [comment]
Hey @cesards, I have less time these days to maintain it. Happy to receive PRs though if you feel like it. The biggest thing I'd like to be able to do is re-adapt to the latest changes that github made to their pages.

**Comment by artisologic** [comment]
@cesards The latest version (1.0.3) brings back full compatibility for the https://github.com/stars page. Sorry for the wait.
